#array_width = 60
#attr_fn_like_width = 70
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
#chain_width = 60
color = "Always"
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = false
control_brace_style = "AlwaysNextLine"
disable_all_formatting = false
doc_comment_code_block_width = 140
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 30
error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = "Vertical"
#fn_call_width = 60
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = false
group_imports = "StdExternalCrate"
hard_tabs = true
hex_literal_case = "Upper"
hide_parse_errors = false
ignore = []
imports_granularity = "Crate"
imports_indent = "Visual"
imports_layout = "Vertical"
indent_style = "Visual"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 140
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
#required_version = "1.4.38"
short_array_element_width_threshold = 10
#single_line_if_else_max_width = 50
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 30
struct_lit_single_line = true
#struct_lit_width = 30
#struct_variant_width = 35
tab_spaces = 100
trailing_comma = "Vertical"
trailing_semicolon = false
type_punctuation_density = "Wide"
unstable_features = false
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = true
#version = "Two"
where_single_line = true
wrap_comments = true

#emit_mode = "Files"
#make_backup = false
#print_misformatted_file_names = false
